In [43]:
from euroleague_api.boxscore_data import BoxScoreData
from euroleague_api.game_stats import GameStats
from euroleague_api.play_by_play_data import PlayByPlay
from euroleague_api.player_stats import PlayerStats
from euroleague_api.shot_data import ShotData
from euroleague_api.standings import Standings
from euroleague_api.team_stats import TeamStats
from euroleague_api.schedule import Schedule
import pandas as pd

In [27]:
season = 2024
#roundid = 28
competition_code = "E"

In [41]:
sh = Schedule(competition="E")
bs = BoxScoreData(competition="E")

In [34]:
schedule = sh.get_schedule(season=season)

In [42]:
boxscores = pd.read_csv('boxscores_2024.csv')

In [36]:
schedule

,gameday,round,arenacode,arenaname,arenacapacity,date,startime,endtime,group,game,gamecode,hometeam,homecode,hometv,awayteam,awaycode,awaytv,confirmeddate,confirmedtime,played
0,1,RS,ASY,UBER ARENA,14500,"Oct 03, 2024",18:45,22:15,Regular Season,1,E2024_1,ALBA BERLIN,BER,BER,PANATHINAIKOS AKTOR ATHENS,PAN,PAO,true,true,true
1,1,RS,ATJ,ZALGIRIO ARENA,15415,"Oct 03, 2024",19:00,22:30,Regular Season,3,E2024_3,ZALGIRIS KAUNAS,ZAL,ZAL,FC BARCELONA,BAR,BAR,true,true,true
2,1,RS,AAM,UNIPOL ARENA,11000,"Oct 04, 2024",21:00,00:30,Regular Season,9,E2024_9,VIRTUS SEGAFREDO BOLOGNA,VIR,VIR,ANADOLU EFES ISTANBUL,IST,EFS,true,true,true
3,1,RS,AUR,SALLE GASTON MEDECIN,4090,"Oct 03, 2024",19:00,22:30,Regular Season,2,E2024_2,AS MONACO,MCO,ASM,EA7 EMPORIO ARMANI MILAN,MIL,EA7,true,true,true
4,1,RS,AVB1,ADIDAS ARENA,8000,"Oct 04, 2024",21:00,00:30,Regular Season,8,E2024_8,PARIS BASKETBALL,PRS,PBB,CRVENA ZVEZDA MERIDIANBET BELGRADE,RED,CZV,true,true,true
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,41,PO,AUR,SALLE GASTON MEDECIN,4090,"May 06, 2025",19:00,22:30,PLAYOFF B,325,E2024_325,AS MONACO,MCO,ASM,FC BARCELONA,BAR,BAR,true,true,true
326,42,FF,AVH,ETIHAD ARENA,12000,"May 23, 2025",17:00,20:30,SEMIFINAL B,328,E2024_328,FENERBAHCE BEKO ISTANBUL,ULK,FBB,PANATHINAIKOS AKTOR ATHENS,PAN,PAO,true,true,true
327,42,FF,AVH,ETIHAD ARENA,12000,"May 23, 2025",20:00,23:30,SEMIFINAL A,327,E2024_327,OLYMPIACOS PIRAEUS,OLY,OLY,AS MONACO,MCO,ASM,true,true,true
328,43,FF,AVH,ETIHAD ARENA,12000,"May 25, 2025",19:00,22:30,CHAMPIONSHIP GAME,330,E2024_330,AS MONACO,MCO,ASM,FENERBAHCE BEKO ISTANBUL,ULK,FBB,true,true,true
329,43,FF,AVH,ETIHAD ARENA,12000,"May 25, 2025",16:00,19:30,THIRD PLACE GAME,329,E2024_329,OLYMPIACOS PIRAEUS,OLY,OLY,PANATHINAIKOS AKTOR ATHENS,PAN,PAO,true,true,true

In [39]:
schedule['game'] = schedule['game'].astype(int)

In [48]:
schedule['date'] = pd.to_datetime(schedule['date'])

In [49]:
schedule.sort_values(by=['game'])

,gameday,round,arenacode,arenaname,arenacapacity,date,startime,endtime,group,game,gamecode,hometeam,homecode,hometv,awayteam,awaycode,awaytv,confirmeddate,confirmedtime,played
0,1,RS,ASY,UBER ARENA,14500,2024-10-03,18:45,22:15,Regular Season,1,E2024_1,ALBA BERLIN,BER,BER,PANATHINAIKOS AKTOR ATHENS,PAN,PAO,true,true,true
3,1,RS,AUR,SALLE GASTON MEDECIN,4090,2024-10-03,19:00,22:30,Regular Season,2,E2024_2,AS MONACO,MCO,ASM,EA7 EMPORIO ARMANI MILAN,MIL,EA7,true,true,true
1,1,RS,ATJ,ZALGIRIO ARENA,15415,2024-10-03,19:00,22:30,Regular Season,3,E2024_3,ZALGIRIS KAUNAS,ZAL,ZAL,FC BARCELONA,BAR,BAR,true,true,true
7,1,RS,AUC,BUESA ARENA,15431,2024-10-03,20:30,00:00,Regular Season,4,E2024_4,BASKONIA VITORIA-GASTEIZ,BAS,BKN,PARTIZAN MOZZART BET BELGRADE,PAR,PAR,true,true,true
8,1,RS,AVE,SAP GARDEN,11500,2024-10-03,20:45,00:15,Regular Season,5,E2024_5,FC BAYERN MUNICH,MUN,BAY,REAL MADRID,MAD,RMB,true,true,true
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,41,PO,AUM,OAKA Altion,18310,2025-05-06,20:45,00:15,PLAYOFF C,326,E2024_326,PANATHINAIKOS AKTOR ATHENS,PAN,PAO,ANADOLU EFES ISTANBUL,IST,EFS,true,true,true
327,42,FF,AVH,ETIHAD ARENA,12000,2025-05-23,20:00,23:30,SEMIFINAL A,327,E2024_327,OLYMPIACOS PIRAEUS,OLY,OLY,AS MONACO,MCO,ASM,true,true,true
326,42,FF,AVH,ETIHAD ARENA,12000,2025-05-23,17:00,20:30,SEMIFINAL B,328,E2024_328,FENERBAHCE BEKO ISTANBUL,ULK,FBB,PANATHINAIKOS AKTOR ATHENS,PAN,PAO,true,true,true
329,43,FF,AVH,ETIHAD ARENA,12000,2025-05-25,16:00,19:30,THIRD PLACE GAME,329,E2024_329,OLYMPIACOS PIRAEUS,OLY,OLY,PANATHINAIKOS AKTOR ATHENS,PAN,PAO,true,true,true
328,43,FF,AVH,ETIHAD ARENA,12000,2025-05-25,19:00,22:30,CHAMPIONSHIP GAME,330,E2024_330,AS MONACO,MCO,ASM,FENERBAHCE BEKO ISTANBUL,ULK,FBB,true,true,true

In [50]:
# merge keeping all boxscores columns plus selected schedule fields
_schedule_cols = ['game','date','startime','endtime','group','hometeam','awayteam']
boxscores_merged = boxscores.merge(schedule[_schedule_cols], how='left', left_on='Gamecode', right_on='game')
boxscores_merged.drop(columns=['game'], inplace=True)
boxscores_merged.head()

,Season,Gamecode,Home,Player_ID,IsStarter,IsPlaying,Team,Dorsal,Player,Minutes,...,FoulsCommited,FoulsReceived,Valuation,Plusminus,date,startime,endtime,group,hometeam,awayteam
0,2024,1,1,P012099,0.0,0.0,BER,2.0,"GROSBER, DORIAN",DNP,...,0,0,0,0.0,2024-10-03,18:45,22:15,Regular Season,ALBA BERLIN,PANATHINAIKOS AKTOR ATHENS
1,2024,1,1,P008173,0.0,0.0,BER,3.0,"SPAGNOLO, MATTEO",16:18,...,2,1,4,-6.0,2024-10-03,18:45,22:15,Regular Season,ALBA BERLIN,PANATHINAIKOS AKTOR ATHENS
2,2024,1,1,P011934,0.0,0.0,BER,5.0,"WETZELL, YANNI",19:03,...,0,1,8,-12.0,2024-10-03,18:45,22:15,Regular Season,ALBA BERLIN,PANATHINAIKOS AKTOR ATHENS
3,2024,1,1,P008062,0.0,0.0,BER,7.0,"MCDOWELL-WHITE, WILL",15:15,...,1,0,12,-8.0,2024-10-03,18:45,22:15,Regular Season,ALBA BERLIN,PANATHINAIKOS AKTOR ATHENS
4,2024,1,1,P007025,1.0,1.0,BER,9.0,"MATTISSECK, JONAS",21:09,...,4,1,1,-7.0,2024-10-03,18:45,22:15,Regular Season,ALBA BERLIN,PANATHINAIKOS AKTOR ATHENS

In [51]:
boxscores_merged.to_csv('boxscores_2024_merged.csv', index=False)

In [45]:
pd.merge(boxscores, schedule, how='left', left_on='Gamecode', right_on='game')

,Season,Gamecode,Home,Player_ID,IsStarter,IsPlaying,Team,Dorsal,Player,Minutes,...,gamecode,hometeam,homecode,hometv,awayteam,awaycode,awaytv,confirmeddate,confirmedtime,played
0,2024,1,1,P012099,0.0,0.0,BER,2.0,"GROSBER, DORIAN",DNP,...,E2024_1,ALBA BERLIN,BER,BER,PANATHINAIKOS AKTOR ATHENS,PAN,PAO,true,true,true
1,2024,1,1,P008173,0.0,0.0,BER,3.0,"SPAGNOLO, MATTEO",16:18,...,E2024_1,ALBA BERLIN,BER,BER,PANATHINAIKOS AKTOR ATHENS,PAN,PAO,true,true,true
2,2024,1,1,P011934,0.0,0.0,BER,5.0,"WETZELL, YANNI",19:03,...,E2024_1,ALBA BERLIN,BER,BER,PANATHINAIKOS AKTOR ATHENS,PAN,PAO,true,true,true
3,2024,1,1,P008062,0.0,0.0,BER,7.0,"MCDOWELL-WHITE, WILL",15:15,...,E2024_1,ALBA BERLIN,BER,BER,PANATHINAIKOS AKTOR ATHENS,PAN,PAO,true,true,true
4,2024,1,1,P007025,1.0,1.0,BER,9.0,"MATTISSECK, JONAS",21:09,...,E2024_1,ALBA BERLIN,BER,BER,PANATHINAIKOS AKTOR ATHENS,PAN,PAO,true,true,true
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9178,2024,330,0,P013696,0.0,0.0,ULK,44.0,"BANGO, JILSON",DNP,...,E2024_330,AS MONACO,MCO,ASM,FENERBAHCE BEKO ISTANBUL,ULK,FBB,true,true,true
9179,2024,330,0,P009783,1.0,0.0,ULK,50.0,"COLSON, BONZIE",03:54,...,E2024_330,AS MONACO,MCO,ASM,FENERBAHCE BEKO ISTANBUL,ULK,FBB,true,true,true
9180,2024,330,0,P007182,1.0,1.0,ULK,92.0,"BIRCH, KHEM",20:16,...,E2024_330,AS MONACO,MCO,ASM,FENERBAHCE BEKO ISTANBUL,ULK,FBB,true,true,true
9181,2024,330,0,Team,0.0,0.0,ULK,NaN,Team,NaN,...,E2024_330,AS MONACO,MCO,ASM,FENERBAHCE BEKO ISTANBUL,ULK,FBB,true,true,true
9182,2024,330,0,Total,NaN,NaN,ULK,NaN,Total,200:00,...,E2024_330,AS MONACO,MCO,ASM,FENERBAHCE BEKO ISTANBUL,ULK,FBB,true,true,true

In [ ]:
from euroleague_api.EuroLeagueData import EuroLeagueData

In [12]:
from euroleague_api.EuroLeagueData import EuroLeagueData
from euroleague_api.boxscore_data import BoxScoreData# get_players_boxscore_stats
import pandas as pd

In [14]:
gamecodes = gs.get_gamecodes_season(season=2024)

In [15]:
gs = BoxScoreData(competition="E")

In [16]:
import time

In [17]:
boxscores = pd.DataFrame()
for code in list(gamecodes['gameCode']):
    game_df = gs.get_players_boxscore_stats(season=2024, gamecode=code)
    boxscores = pd.concat([boxscores, game_df], ignore_index=True)
    time.sleep(3)

In [ ]:
boxscores.to_csv('boxscores_2024.csv', index=False)

In [23]:
boxscores

,Season,Gamecode,Home,Player_ID,IsStarter,IsPlaying,Team,Dorsal,Player,Minutes,...,TotalRebounds,Assistances,Steals,Turnovers,BlocksFavour,BlocksAgainst,FoulsCommited,FoulsReceived,Valuation,Plusminus
0,2024,1,1,P012099,0.0,0.0,BER,2,"GROSBER, DORIAN",DNP,...,0,0,0,0,0,0,0,0,0,0.0
1,2024,1,1,P008173,0.0,0.0,BER,3,"SPAGNOLO, MATTEO",16:18,...,1,2,0,1,0,0,2,1,4,-6.0
2,2024,1,1,P011934,0.0,0.0,BER,5,"WETZELL, YANNI",19:03,...,7,0,0,2,0,0,0,1,8,-12.0
3,2024,1,1,P008062,0.0,0.0,BER,7,"MCDOWELL-WHITE, WILL",15:15,...,1,1,0,1,0,0,1,0,12,-8.0
4,2024,1,1,P007025,1.0,1.0,BER,9,"MATTISSECK, JONAS",21:09,...,1,0,1,0,0,1,4,1,1,-7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9178,2024,330,0,P013696,0.0,0.0,ULK,44,"BANGO, JILSON",DNP,...,0,0,0,0,0,0,0,0,0,0.0
9179,2024,330,0,P009783,1.0,0.0,ULK,50,"COLSON, BONZIE",03:54,...,0,0,0,1,0,0,0,0,-1,-7.0
9180,2024,330,0,P007182,1.0,1.0,ULK,92,"BIRCH, KHEM",20:16,...,6,0,0,1,1,0,3,0,3,3.0
9181,2024,330,0,Team,0.0,0.0,ULK,,Team,None,...,4,0,0,2,0,0,0,0,2,NaN
9182,2024,330,0,Total,NaN,NaN,ULK,NaN,Total,200:00,...,38,8,8,9,2,1,23,25,90,NaN